name: Manual start test.py
env:
  github_token: ${{ secrets.GITHUB_TOKEN }}
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: First job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install gitpython
        run: |
          python3 -m pip install gitpython
      - name: testing
        run: python res/src/new_checkdirectlinks.py
