name: Manual unzip
on: 
  workflow_dispatch:
jobs:
  First:
    name: First job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
       - name: Unzip a file
         run: |
          import os
          from zipfile import ZipFile
          with ZipFile("zip.zip", 'r') as zObject:
		       zObject.extractall()
         shell: python
      - name: Commit file
        run: |
          git config user.name "zuckung" 
          git config user.email "zuckung@gmx.de"
          git add .
          git commit -m "unzipped" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true